site_name: Pait
site_description: Pait is a Python api tool. Pait enables your Python web framework to have type checking, parameter type conversion, interface document generation and can display your documents through Redoc or Swagger (power by inspect, pydantic)

theme:
    name: material
    language: zh
    features:
        - navigation.top
        - content.code.annotate

repo_name: so1n/pait
repo_url: https://github.com/so1n/pait
edit_uri: ""


nav:
  - 介绍: 'index.md'
  - 类型转换与参数校验:
    - 介绍: '1_1_introduction.md'
    - 如何使用Field: '1_2_how_to_use_field.md'
    - 如何使用Type: '1_3_how_to_use_type.md'
    - Depend: '1_4_depend.md'
    - 异常提示: '1_5_exception.md'
  - Pait的复用: '2_pait_multiplexing.md'
  - API文档:
    - 介绍: '3_1_introduction.md'
    - OpenApi生成: '3_2_openapi.md'
    - OpenApi路由使用: '3_3_openapi_route.md'
    - 其它文档: '3_4_other_docs.md'
  - 单元测试支持: '4_unit_test_helper.md'
  - 插件:
      - 介绍: '5_1_introduction.md'
      - 参数检查插件: '5_2_param_check_plugin.md'
      - Json响应插件: '5_3_json_response_plugin.md'
      - Mock响应插件: '5_4_mock_json_response_check_plugin.md'
      - 如何自定义插件: '5_5_how_tp_customize_the_plugin.md'
  - 其它: "6_other.md"

extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/so1n
plugins:
    - search:
        lang:
            - en
markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
