site_name: Pait
site_description: Pait(π tool) - Python Modern API Tools, easier to use web frameworks/write API routing

theme:
    name: material
    language: en
    logo: assets/logo.png
    favicon: assets/images/favicon.png
    features:
        - content.code.annotate
        - navigation.top
        - navigation.path
        - search.highlight
        - search.share
        - search.suggest
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

repo_name: so1n/pait
repo_url: https://github.com/so1n/pait
edit_uri: ""


nav:
  - Introduction: 'index.md'
  - Type conversion and parameter validation:
    - Introduction: '1_1_introduction.md'
    - How to use Field: '1_2_how_to_use_field.md'
    - Hot to use Type: '1_3_how_to_use_type.md'
    - Depend: '1_4_depend.md'
    - Exception: '1_5_exception.md'
  - Pait multiplexing: '2_pait_multiplexing.md'
  - API doc: '3_api_doc.md'
  - Unit test helper: '4_unit_test_helper.md'
  - Plugin:
      - Introduction: '5_1_introduction.md'
      - Param check plugin: '5_2_param_check_plugin.md'
      - Json Response plugin: '5_3_json_response_plugin.md'
      - Mock Response plugin: '5_4_mock_json_response_check_plugin.md'
      - How to customize plugin: '5_5_how_to_customize_plugin.md'
  - config: "6_config.md"
  - gRPC Gateway: "7_gRPC_gateway.md"
  - Other: "8_other.md"

extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /pait/
      lang: en
    - name: 中文
      link: /pait-zh-doc/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/so1n
plugins:
    - search:
        lang:
            - en
markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
