site_name: Pait
site_description: Pait(π tool) - Python Modern API Tools, easier to use web frameworks/write API routing

theme:
    name: material
    language: en
    logo: assets/logo.png
    favicon: assets/images/favicon.png
    features:
        - content.code.annotate
        - content.code.copy
        - content.tabs.link
        - navigation.top
        - navigation.path
        - search.highlight
        - search.share
        - search.suggest
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

repo_name: so1n/pait
repo_url: https://github.com/so1n/pait
edit_uri: ""


nav:
  - Introduction: 'index.md'
  - Type conversion and parameter validation:
    - Introduction: '1_1_introduction.md'
    - How to use Field: '1_2_how_to_use_field.md'
    - How to use Type: '1_3_how_to_use_type.md'
    - Streaming files: '1_4_streaming_files.md'
    - Depend: '1_5_depend.md'
    - Exception: '1_6_exception.md'
  - How to use Pait decorator: '2_how_to_use_pait.md'
  - APIRoute: '3_api_route.md'
  - OpenAPI:
      - OpenAPI: '4_1_openapi.md'
      - OpenAPI Route: '4_2_openapi_route.md'
      - Security: '4_3_security.md'
  - MCP: '5_mcp.md'
  - Unit test helper: '6_unit_test_helper.md'
  - Plugin:
      - Introduction: '7_1_introduction.md'
      - Parameter checking plugin: '7_2_param_check_plugin.md'
      - Json response plugin: '7_3_json_response_plugin.md'
      - Mock response plugin: '7_4_mock_json_response_check_plugin.md'
      - Response caching plugin: '7_5_cache_response.md'
      - How to customize plugins: '7_x_how_to_customize_the_plugin.md'
  - config: "8_config.md"
  # - ecosystem: "9_ecosystem.md"
  - Other: "10_other.md"

extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /pait/
      lang: en
    - name: 中文
      link: /pait-zh-doc/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/so1n
plugins:
    - search:
        lang:
            - en
    - termynal:
        prompt_literal_start:
          - "$"
          - ">"
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - meta
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
extra_css:
  - stylesheets/extra.css
