# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tapi.proto\x12\x08pait.api\x1a google/protobuf/descriptor.proto"\xde\x03\n\x07\x41piRule\x12#\n\x03get\x18\x02 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12#\n\x03put\x18\x03 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12$\n\x04post\x18\x04 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12&\n\x06\x64\x65lete\x18\x05 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12%\n\x05patch\x18\x06 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12-\n\x06\x63ustom\x18\x08 \x01(\x0b\x32\x1b.pait.api.CustomHttpPatternH\x00\x12#\n\x03\x61ny\x18\t \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\x15\n\rresponse_body\x18\x0c \x01(\t\x12.\n\x13\x61\x64\x64itional_bindings\x18\x0b \x03(\x0b\x32\x11.pait.api.ApiRule\x12\r\n\x05group\x18\x15 \x01(\t\x12\x1a\n\x03tag\x18\x16 \x03(\x0b\x32\r.pait.api.Tag\x12\x0f\n\x07summary\x18\x17 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x18 \x01(\t\x12\x12\n\nnot_enable\x18\x19 \x01(\x08\x42\r\n\x0bhttp_method"[\n\x11\x43ustomHttpPattern\x12"\n\x04kind\x18\x01 \x01(\x0b\x32\x14.pait.api.HttpMethod\x12"\n\x04path\x18\x02 \x01(\x0b\x32\x14.pait.api.HttpMethod"!\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t":\n\nHttpMethod\x12\r\n\x03url\x18\x01 \x01(\tH\x00\x12\x11\n\x07\x64\x65\x66\x61ult\x18\x02 \x01(\x08H\x00\x42\n\n\x08http_url:B\n\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xb1\xca\xbc" \x01(\x0b\x32\x11.pait.api.ApiRuleb\x06proto3'
)


HTTP_FIELD_NUMBER = 72295729
http = DESCRIPTOR.extensions_by_name["http"]

_APIRULE = DESCRIPTOR.message_types_by_name["ApiRule"]
_CUSTOMHTTPPATTERN = DESCRIPTOR.message_types_by_name["CustomHttpPattern"]
_TAG = DESCRIPTOR.message_types_by_name["Tag"]
_HTTPMETHOD = DESCRIPTOR.message_types_by_name["HttpMethod"]
ApiRule = _reflection.GeneratedProtocolMessageType(
    "ApiRule",
    (_message.Message,),
    {
        "DESCRIPTOR": _APIRULE,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:pait.api.ApiRule)
    },
)
_sym_db.RegisterMessage(ApiRule)

CustomHttpPattern = _reflection.GeneratedProtocolMessageType(
    "CustomHttpPattern",
    (_message.Message,),
    {
        "DESCRIPTOR": _CUSTOMHTTPPATTERN,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:pait.api.CustomHttpPattern)
    },
)
_sym_db.RegisterMessage(CustomHttpPattern)

Tag = _reflection.GeneratedProtocolMessageType(
    "Tag",
    (_message.Message,),
    {
        "DESCRIPTOR": _TAG,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:pait.api.Tag)
    },
)
_sym_db.RegisterMessage(Tag)

HttpMethod = _reflection.GeneratedProtocolMessageType(
    "HttpMethod",
    (_message.Message,),
    {
        "DESCRIPTOR": _HTTPMETHOD,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:pait.api.HttpMethod)
    },
)
_sym_db.RegisterMessage(HttpMethod)

if _descriptor._USE_C_DESCRIPTORS == False:
    google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(http)

    DESCRIPTOR._options = None
    _APIRULE._serialized_start = 58
    _APIRULE._serialized_end = 536
    _CUSTOMHTTPPATTERN._serialized_start = 538
    _CUSTOMHTTPPATTERN._serialized_end = 629
    _TAG._serialized_start = 631
    _TAG._serialized_end = 664
    _HTTPMETHOD._serialized_start = 666
    _HTTPMETHOD._serialized_end = 724
# @@protoc_insertion_point(module_scope)
