"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import example_proto.other.other_pb2
import google.protobuf.empty_pb2
import grpc

class OtherStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    nested_demo: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        example_proto.other.other_pb2.NestedMessage]
    """pait: {"http_method": "POST", "url": "/other/nested-demo"}
    pait: {"response_message": {"nested": "/map_demo/${}/repeated_demo/$[]/$.map_demo/${}/repeated_demo"}}
    """


class OtherServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def nested_demo(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> example_proto.other.other_pb2.NestedMessage:
        """pait: {"http_method": "POST", "url": "/other/nested-demo"}
        pait: {"response_message": {"nested": "/map_demo/${}/repeated_demo/$[]/$.map_demo/${}/repeated_demo"}}
        """
        pass


def add_OtherServicer_to_server(servicer: OtherServicer, server: grpc.Server) -> None: ...
