# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_proto/other/other.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x65xample_proto/other/other.proto\x12\x0cother_social\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x0b\x44\x65moMessage\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\t\"J\n\x16SubSubSubNestedMessage\x12\x30\n\rrepeated_demo\x18\x01 \x03(\x0b\x32\x19.other_social.DemoMessage\"\xad\x01\n\x13SubSubNestedMessage\x12@\n\x08map_demo\x18\x01 \x03(\x0b\x32..other_social.SubSubNestedMessage.MapDemoEntry\x1aT\n\x0cMapDemoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.other_social.SubSubSubNestedMessage:\x02\x38\x01\"L\n\x10SubNestedMessage\x12\x38\n\rrepeated_demo\x18\x01 \x03(\x0b\x32!.other_social.SubSubNestedMessage\"\x9b\x01\n\rNestedMessage\x12:\n\x08map_demo\x18\x01 \x03(\x0b\x32(.other_social.NestedMessage.MapDemoEntry\x1aN\n\x0cMapDemoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.other_social.SubNestedMessage:\x02\x38\x01\x32K\n\x05Other\x12\x42\n\x0bnested_demo\x12\x16.google.protobuf.Empty\x1a\x1b.other_social.NestedMessageb\x06proto3')



_DEMOMESSAGE = DESCRIPTOR.message_types_by_name['DemoMessage']
_SUBSUBSUBNESTEDMESSAGE = DESCRIPTOR.message_types_by_name['SubSubSubNestedMessage']
_SUBSUBNESTEDMESSAGE = DESCRIPTOR.message_types_by_name['SubSubNestedMessage']
_SUBSUBNESTEDMESSAGE_MAPDEMOENTRY = _SUBSUBNESTEDMESSAGE.nested_types_by_name['MapDemoEntry']
_SUBNESTEDMESSAGE = DESCRIPTOR.message_types_by_name['SubNestedMessage']
_NESTEDMESSAGE = DESCRIPTOR.message_types_by_name['NestedMessage']
_NESTEDMESSAGE_MAPDEMOENTRY = _NESTEDMESSAGE.nested_types_by_name['MapDemoEntry']
DemoMessage = _reflection.GeneratedProtocolMessageType('DemoMessage', (_message.Message,), {
  'DESCRIPTOR' : _DEMOMESSAGE,
  '__module__' : 'example_proto.other.other_pb2'
  # @@protoc_insertion_point(class_scope:other_social.DemoMessage)
  })
_sym_db.RegisterMessage(DemoMessage)

SubSubSubNestedMessage = _reflection.GeneratedProtocolMessageType('SubSubSubNestedMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBSUBSUBNESTEDMESSAGE,
  '__module__' : 'example_proto.other.other_pb2'
  # @@protoc_insertion_point(class_scope:other_social.SubSubSubNestedMessage)
  })
_sym_db.RegisterMessage(SubSubSubNestedMessage)

SubSubNestedMessage = _reflection.GeneratedProtocolMessageType('SubSubNestedMessage', (_message.Message,), {

  'MapDemoEntry' : _reflection.GeneratedProtocolMessageType('MapDemoEntry', (_message.Message,), {
    'DESCRIPTOR' : _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY,
    '__module__' : 'example_proto.other.other_pb2'
    # @@protoc_insertion_point(class_scope:other_social.SubSubNestedMessage.MapDemoEntry)
    })
  ,
  'DESCRIPTOR' : _SUBSUBNESTEDMESSAGE,
  '__module__' : 'example_proto.other.other_pb2'
  # @@protoc_insertion_point(class_scope:other_social.SubSubNestedMessage)
  })
_sym_db.RegisterMessage(SubSubNestedMessage)
_sym_db.RegisterMessage(SubSubNestedMessage.MapDemoEntry)

SubNestedMessage = _reflection.GeneratedProtocolMessageType('SubNestedMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBNESTEDMESSAGE,
  '__module__' : 'example_proto.other.other_pb2'
  # @@protoc_insertion_point(class_scope:other_social.SubNestedMessage)
  })
_sym_db.RegisterMessage(SubNestedMessage)

NestedMessage = _reflection.GeneratedProtocolMessageType('NestedMessage', (_message.Message,), {

  'MapDemoEntry' : _reflection.GeneratedProtocolMessageType('MapDemoEntry', (_message.Message,), {
    'DESCRIPTOR' : _NESTEDMESSAGE_MAPDEMOENTRY,
    '__module__' : 'example_proto.other.other_pb2'
    # @@protoc_insertion_point(class_scope:other_social.NestedMessage.MapDemoEntry)
    })
  ,
  'DESCRIPTOR' : _NESTEDMESSAGE,
  '__module__' : 'example_proto.other.other_pb2'
  # @@protoc_insertion_point(class_scope:other_social.NestedMessage)
  })
_sym_db.RegisterMessage(NestedMessage)
_sym_db.RegisterMessage(NestedMessage.MapDemoEntry)

_OTHER = DESCRIPTOR.services_by_name['Other']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._options = None
  _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._serialized_options = b'8\001'
  _NESTEDMESSAGE_MAPDEMOENTRY._options = None
  _NESTEDMESSAGE_MAPDEMOENTRY._serialized_options = b'8\001'
  _DEMOMESSAGE._serialized_start=78
  _DEMOMESSAGE._serialized_end=113
  _SUBSUBSUBNESTEDMESSAGE._serialized_start=115
  _SUBSUBSUBNESTEDMESSAGE._serialized_end=189
  _SUBSUBNESTEDMESSAGE._serialized_start=192
  _SUBSUBNESTEDMESSAGE._serialized_end=365
  _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._serialized_start=281
  _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._serialized_end=365
  _SUBNESTEDMESSAGE._serialized_start=367
  _SUBNESTEDMESSAGE._serialized_end=443
  _NESTEDMESSAGE._serialized_start=446
  _NESTEDMESSAGE._serialized_end=601
  _NESTEDMESSAGE_MAPDEMOENTRY._serialized_start=523
  _NESTEDMESSAGE_MAPDEMOENTRY._serialized_end=601
  _OTHER._serialized_start=603
  _OTHER._serialized_end=678
# @@protoc_insertion_point(module_scope)
