# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_proto_by_option/common/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example_proto_by_option/common/api.proto',
  package='pait.api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(example_proto_by_option/common/api.proto\x12\x08pait.api\x1a google/protobuf/descriptor.proto\"\xee\x03\n\x07\x41piRule\x12#\n\x03get\x18\x02 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12#\n\x03put\x18\x03 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12$\n\x04post\x18\x04 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12&\n\x06\x64\x65lete\x18\x05 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12%\n\x05patch\x18\x06 \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12-\n\x06\x63ustom\x18\x08 \x01(\x0b\x32\x1b.pait.api.CustomHttpPatternH\x00\x12#\n\x03\x61ny\x18\t \x01(\x0b\x32\x14.pait.api.HttpMethodH\x00\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\x15\n\rresponse_body\x18\x0c \x01(\t\x12.\n\x13\x61\x64\x64itional_bindings\x18\x0b \x03(\x0b\x32\x11.pait.api.ApiRule\x12\r\n\x05group\x18\x15 \x01(\t\x12\x1a\n\x03tag\x18\x16 \x03(\x0b\x32\r.pait.api.Tag\x12\x0f\n\x07summary\x18\x17 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x18 \x01(\t\x12\x12\n\nnot_enable\x18\x19 \x01(\x08\x12\x0e\n\x06\x61uthor\x18\x1a \x03(\tB\r\n\x0bhttp_method\"[\n\x11\x43ustomHttpPattern\x12\"\n\x04kind\x18\x01 \x01(\x0b\x32\x14.pait.api.HttpMethod\x12\"\n\x04path\x18\x02 \x01(\x0b\x32\x14.pait.api.HttpMethod\"!\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\":\n\nHttpMethod\x12\r\n\x03url\x18\x01 \x01(\tH\x00\x12\x11\n\x07\x64\x65\x66\x61ult\x18\x02 \x01(\x08H\x00\x42\n\n\x08http_url:B\n\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xb1\xca\xbc\" \x01(\x0b\x32\x11.pait.api.ApiRuleb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


HTTP_FIELD_NUMBER = 72295729
http = _descriptor.FieldDescriptor(
  name='http', full_name='pait.api.http', index=0,
  number=72295729, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_APIRULE = _descriptor.Descriptor(
  name='ApiRule',
  full_name='pait.api.ApiRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='get', full_name='pait.api.ApiRule.get', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='put', full_name='pait.api.ApiRule.put', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='post', full_name='pait.api.ApiRule.post', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete', full_name='pait.api.ApiRule.delete', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='patch', full_name='pait.api.ApiRule.patch', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom', full_name='pait.api.ApiRule.custom', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='any', full_name='pait.api.ApiRule.any', index=6,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='pait.api.ApiRule.body', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_body', full_name='pait.api.ApiRule.response_body', index=8,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='additional_bindings', full_name='pait.api.ApiRule.additional_bindings', index=9,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group', full_name='pait.api.ApiRule.group', index=10,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='pait.api.ApiRule.tag', index=11,
      number=22, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summary', full_name='pait.api.ApiRule.summary', index=12,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='pait.api.ApiRule.desc', index=13,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='not_enable', full_name='pait.api.ApiRule.not_enable', index=14,
      number=25, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='pait.api.ApiRule.author', index=15,
      number=26, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='http_method', full_name='pait.api.ApiRule.http_method',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=89,
  serialized_end=583,
)


_CUSTOMHTTPPATTERN = _descriptor.Descriptor(
  name='CustomHttpPattern',
  full_name='pait.api.CustomHttpPattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='pait.api.CustomHttpPattern.kind', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='pait.api.CustomHttpPattern.path', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=676,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='pait.api.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pait.api.Tag.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='pait.api.Tag.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=711,
)


_HTTPMETHOD = _descriptor.Descriptor(
  name='HttpMethod',
  full_name='pait.api.HttpMethod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='pait.api.HttpMethod.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default', full_name='pait.api.HttpMethod.default', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='http_url', full_name='pait.api.HttpMethod.http_url',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=713,
  serialized_end=771,
)

_APIRULE.fields_by_name['get'].message_type = _HTTPMETHOD
_APIRULE.fields_by_name['put'].message_type = _HTTPMETHOD
_APIRULE.fields_by_name['post'].message_type = _HTTPMETHOD
_APIRULE.fields_by_name['delete'].message_type = _HTTPMETHOD
_APIRULE.fields_by_name['patch'].message_type = _HTTPMETHOD
_APIRULE.fields_by_name['custom'].message_type = _CUSTOMHTTPPATTERN
_APIRULE.fields_by_name['any'].message_type = _HTTPMETHOD
_APIRULE.fields_by_name['additional_bindings'].message_type = _APIRULE
_APIRULE.fields_by_name['tag'].message_type = _TAG
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['get'])
_APIRULE.fields_by_name['get'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['put'])
_APIRULE.fields_by_name['put'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['post'])
_APIRULE.fields_by_name['post'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['delete'])
_APIRULE.fields_by_name['delete'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['patch'])
_APIRULE.fields_by_name['patch'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['custom'])
_APIRULE.fields_by_name['custom'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_APIRULE.oneofs_by_name['http_method'].fields.append(
  _APIRULE.fields_by_name['any'])
_APIRULE.fields_by_name['any'].containing_oneof = _APIRULE.oneofs_by_name['http_method']
_CUSTOMHTTPPATTERN.fields_by_name['kind'].message_type = _HTTPMETHOD
_CUSTOMHTTPPATTERN.fields_by_name['path'].message_type = _HTTPMETHOD
_HTTPMETHOD.oneofs_by_name['http_url'].fields.append(
  _HTTPMETHOD.fields_by_name['url'])
_HTTPMETHOD.fields_by_name['url'].containing_oneof = _HTTPMETHOD.oneofs_by_name['http_url']
_HTTPMETHOD.oneofs_by_name['http_url'].fields.append(
  _HTTPMETHOD.fields_by_name['default'])
_HTTPMETHOD.fields_by_name['default'].containing_oneof = _HTTPMETHOD.oneofs_by_name['http_url']
DESCRIPTOR.message_types_by_name['ApiRule'] = _APIRULE
DESCRIPTOR.message_types_by_name['CustomHttpPattern'] = _CUSTOMHTTPPATTERN
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['HttpMethod'] = _HTTPMETHOD
DESCRIPTOR.extensions_by_name['http'] = http
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApiRule = _reflection.GeneratedProtocolMessageType('ApiRule', (_message.Message,), {
  'DESCRIPTOR' : _APIRULE,
  '__module__' : 'example_proto_by_option.common.api_pb2'
  # @@protoc_insertion_point(class_scope:pait.api.ApiRule)
  })
_sym_db.RegisterMessage(ApiRule)

CustomHttpPattern = _reflection.GeneratedProtocolMessageType('CustomHttpPattern', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMHTTPPATTERN,
  '__module__' : 'example_proto_by_option.common.api_pb2'
  # @@protoc_insertion_point(class_scope:pait.api.CustomHttpPattern)
  })
_sym_db.RegisterMessage(CustomHttpPattern)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), {
  'DESCRIPTOR' : _TAG,
  '__module__' : 'example_proto_by_option.common.api_pb2'
  # @@protoc_insertion_point(class_scope:pait.api.Tag)
  })
_sym_db.RegisterMessage(Tag)

HttpMethod = _reflection.GeneratedProtocolMessageType('HttpMethod', (_message.Message,), {
  'DESCRIPTOR' : _HTTPMETHOD,
  '__module__' : 'example_proto_by_option.common.api_pb2'
  # @@protoc_insertion_point(class_scope:pait.api.HttpMethod)
  })
_sym_db.RegisterMessage(HttpMethod)

http.message_type = _APIRULE
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(http)

# @@protoc_insertion_point(module_scope)
